language: python
python:
    - '3.6'

services:
    - docker

addons:
    ssh_known_hosts: ssh.pythonanywhere.com

before_install:
   - openssl aes-256-cbc -K $encrypted_509cf6f5306c_key -iv $encrypted_509cf6f5306c_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d

install:
    - pip install -r docker/requirements-dev.txt

env:
    - PYTHONPATH=/home/travis/build/gcallah/Emu86

script:
    - make all_tests

after_success:
   - cd /home/travis/build/gcallah/Emu86; ./deploy.sh

deploy:
  provider: pypi
  user: __token__
  password: $pypi_key
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_COMMIT_MESSAGE == "pypi release v"*

notifications:
  slack: emu86:PJWVpwvXaU6dpB2VeD6UuBzf
