# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_addr', models.CharField(blank=True, default='', max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('descr', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('header', models.CharField(default='', max_length=128)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
