# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-13 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_addr', models.CharField(blank=True, default='', max_length=80, null=True)),
            ],
        ),
    ]
