# Generated by Django 2.0.7 on 2018-08-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emu86', '0003_auto_20180823_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
