# Generated by Django 4.2.25 on 2025-10-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emu86', '0004_auto_20180823_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='site',
            name='url',
        ),
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(default='intel', editable=False, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
