# Generated by Django 4.2.25 on 2025-11-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emu86', '0005_remove_site_descr_remove_site_url_site_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='slug',
        ),
        migrations.AddField(
            model_name='site',
            name='descr',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='url',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='adminemail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
