name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: chmod +x setup.sh all_tests.sh
      - run: ./setup.sh
      - run: ./all_tests.sh